name: Test Mesa Documentation Build

on:
  push:
    branches:
      - 'main'
  schedule:
    # Every Monday at 05:00 UTC
    - cron: "0 5 * * 1"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hawkmoth: [ {version: 'hawkmoth===0.16.0', name: 'fixed'}, {version: 'hawkmoth', name: 'latest' }, {version: 'git+https://github.com/jnikula/hawkmoth.git', name: 'git'} ]
        sphinx: [ {version: 'sphinx===5.1.1', name: 'fixed'}, {version: 'sphinx', name: 'latest'} ]
    steps:
      - name: Install dependencies (apt)
        run: sudo apt-get install -y python3-clang coreutils graphviz
      - name: Install dependencies (pip)
        run: |
          python3 -m venv --system-site-packages .venv
          . .venv/bin/activate
          pip install --upgrade --upgrade-strategy eager ${{ matrix.sphinx.version }} ${{ matrix.hawkmoth.version }} mako===1.2.3
      - name: Clone Mesa
        run: git clone --depth=1 https://gitlab.freedesktop.org/mesa/mesa.git
      - name: Build docs
        run: |
          . .venv/bin/activate
          cd mesa
          sphinx-build -d doctrees -b html docs public
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.sphinx.name }}.${{ matrix.hawkmoth.name }}
          path: mesa/public
          if-no-files-found: error
  compare:
    name: Compare
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: .
      - run: find
      - run: diff -r fixed.fixed fixed.latest
      - run: diff -r fixed.latest fixed.git
      - run: diff -r latest.fixed latest.latest
      - run: diff -r latest.latest latest.git
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
           path: .
      - id: deployment
        uses: actions/deploy-pages@v1
